FROM openjdk
WORKDIR usr/lib
ADD ./target/Musiz_Application_Challenge_c13_s3-0.0.1-SNAPSHOT.jar /usr/lib/Musiz_Application_Challenge_c13_s3-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Musiz_Application_Challenge_c13_s3-0.0.1-SNAPSHOT.jar"]